<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'chat_index' => [[], ['_controller' => 'App\\Controller\\ChatController::index'], [], [['text', '/chat/']], [], []],
    'chat_new' => [[], ['_controller' => 'App\\Controller\\ChatController::new'], [], [['text', '/chat/new']], [], []],
    'chat_show' => [['id'], ['_controller' => 'App\\Controller\\ChatController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/chat']], [], []],
    'chat_edit' => [['id'], ['_controller' => 'App\\Controller\\ChatController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/chat']], [], []],
    'chat_delete' => [['id'], ['_controller' => 'App\\Controller\\ChatController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/chat']], [], []],
    'contact_index' => [[], ['_controller' => 'App\\Controller\\ContactController::index'], [], [['text', '/contact/']], [], []],
    'contact_new' => [[], ['_controller' => 'App\\Controller\\ContactController::new'], [], [['text', '/contact/new']], [], []],
    'contact_show' => [['id'], ['_controller' => 'App\\Controller\\ContactController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/contact']], [], []],
    'contact_edit' => [['id'], ['_controller' => 'App\\Controller\\ContactController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/contact']], [], []],
    'contact_delete' => [['id'], ['_controller' => 'App\\Controller\\ContactController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/contact']], [], []],
    'news_index' => [[], ['_controller' => 'App\\Controller\\NewsController::index'], [], [['text', '/news/']], [], []],
    'news_new' => [[], ['_controller' => 'App\\Controller\\NewsController::new'], [], [['text', '/news/new']], [], []],
    'news_show' => [['id'], ['_controller' => 'App\\Controller\\NewsController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/news']], [], []],
    'news_edit' => [['id'], ['_controller' => 'App\\Controller\\NewsController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/news']], [], []],
    'news_delete' => [['id'], ['_controller' => 'App\\Controller\\NewsController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/news']], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], []],
    'user_index' => [[], ['_controller' => 'App\\Controller\\UserController::index'], [], [['text', '/user/']], [], []],
    'user_new' => [[], ['_controller' => 'App\\Controller\\UserController::new'], [], [['text', '/user/new']], [], []],
    'user_show' => [['id'], ['_controller' => 'App\\Controller\\UserController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/user']], [], []],
    'user_edit' => [['id'], ['_controller' => 'App\\Controller\\UserController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/user']], [], []],
    'user_delete' => [['id'], ['_controller' => 'App\\Controller\\UserController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/user']], [], []],
];
