<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.py4.CGl' shared service.

return $this->privates['.service_locator.py4.CGl'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'news' => ['privates', '.errored..service_locator.py4.CGl.App\\Entity\\News', NULL, 'Cannot autowire service ".service_locator.py4.CGl": it references class "App\\Entity\\News" but no such service exists.'],
], [
    'news' => 'App\\Entity\\News',
]);
